[font]
size = 10.0
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}

[window]
opacity = 0.85
padding = {x = 12, y = 12}
decorations = "none"

[colors]
#default colors
[colors.primary]
background = "#000000"
foreground = "#c0caf5"

#cursor colors
[colors.cursor]
text = "#000000"
cursor = "#ff0000"

#normal colors
[colors.normal]
black   = "#15161e"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"

#bright colors
[colors.bright]
black   = "#414868" 
red     = "#ff0000"
green   = "#9ece6a" 
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#c0caf5"

[terminal.shell]
program = "/usr/bin/zsh"
